[plugin]
id = "first.swag.plugin"
name = ".swaga -> ГОЙДА"
version = "1.0.0"
sdk_version = "1"
author = "@swagnonhewr"
description = "Отправляет ГОЙДА, если отправить .свага"
entry = "index.js"

[permissions]
required = ["messages:send", "events:message"]